# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymacro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 751, 471))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.methodList = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodList.sizePolicy().hasHeightForWidth())
        self.methodList.setSizePolicy(sizePolicy)
        self.methodList.setObjectName("methodList")
        self.gridLayout_2.addWidget(self.methodList, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(251, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.imgTab = QtWidgets.QWidget()
        self.imgTab.setObjectName("imgTab")
        self.imgButton = QtWidgets.QPushButton(self.imgTab)
        self.imgButton.setGeometry(QtCore.QRect(170, 340, 61, 21))
        self.imgButton.setObjectName("imgButton")
        self.clickTargetCheck = QtWidgets.QCheckBox(self.imgTab)
        self.clickTargetCheck.setGeometry(QtCore.QRect(10, 230, 101, 16))
        self.clickTargetCheck.setObjectName("clickTargetCheck")
        self.ImgLabel = QtWidgets.QLabel(self.imgTab)
        self.ImgLabel.setGeometry(QtCore.QRect(10, 10, 226, 181))
        self.ImgLabel.setAutoFillBackground(True)
        self.ImgLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImgLabel.setText("")
        self.ImgLabel.setObjectName("ImgLabel")
        self.ImgNameLabel = QtWidgets.QLabel(self.imgTab)
        self.ImgNameLabel.setGeometry(QtCore.QRect(10, 180, 56, 12))
        self.ImgNameLabel.setLineWidth(0)
        self.ImgNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.ImgNameLabel.setObjectName("ImgNameLabel")
        self.doubleClickCheck = QtWidgets.QCheckBox(self.imgTab)
        self.doubleClickCheck.setEnabled(False)
        self.doubleClickCheck.setGeometry(QtCore.QRect(10, 250, 101, 16))
        self.doubleClickCheck.setCheckable(True)
        self.doubleClickCheck.setTristate(False)
        self.doubleClickCheck.setObjectName("doubleClickCheck")
        self.groupBox = QtWidgets.QGroupBox(self.imgTab)
        self.groupBox.setGeometry(QtCore.QRect(120, 200, 111, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label.setObjectName("label")
        self.loopCountSpin = QtWidgets.QSpinBox(self.groupBox)
        self.loopCountSpin.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.loopCountSpin.setObjectName("loopCountSpin")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.label_3.setObjectName("label_3")
        self.loopCountSpin_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.loopCountSpin_3.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.loopCountSpin_3.setMaximum(10000.0)
        self.loopCountSpin_3.setSingleStep(0.05)
        self.loopCountSpin_3.setProperty("value", 0.2)
        self.loopCountSpin_3.setObjectName("loopCountSpin_3")
        self.clickTargetCheck_2 = QtWidgets.QCheckBox(self.imgTab)
        self.clickTargetCheck_2.setGeometry(QtCore.QRect(10, 210, 101, 16))
        self.clickTargetCheck_2.setObjectName("clickTargetCheck_2")
        self.clickDelayCheck = QtWidgets.QCheckBox(self.imgTab)
        self.clickDelayCheck.setEnabled(False)
        self.clickDelayCheck.setGeometry(QtCore.QRect(10, 270, 101, 16))
        self.clickDelayCheck.setCheckable(True)
        self.clickDelayCheck.setTristate(False)
        self.clickDelayCheck.setObjectName("clickDelayCheck")
        self.clickDelaySpin = QtWidgets.QDoubleSpinBox(self.imgTab)
        self.clickDelaySpin.setEnabled(False)
        self.clickDelaySpin.setGeometry(QtCore.QRect(30, 290, 71, 22))
        self.clickDelaySpin.setMaximum(10000.0)
        self.clickDelaySpin.setSingleStep(0.05)
        self.clickDelaySpin.setProperty("value", 0.2)
        self.clickDelaySpin.setObjectName("clickDelaySpin")
        self.tabWidget.addTab(self.imgTab, "")
        self.funcTab = QtWidgets.QWidget()
        self.funcTab.setObjectName("funcTab")
        self.funcButton = QtWidgets.QPushButton(self.funcTab)
        self.funcButton.setGeometry(QtCore.QRect(320, 460, 61, 21))
        self.funcButton.setObjectName("funcButton")
        self.tabWidget.addTab(self.funcTab, "")
        self.debugTab = QtWidgets.QWidget()
        self.debugTab.setObjectName("debugTab")
        self.tabWidget.addTab(self.debugTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(251, 101))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.onSuccessTab = QtWidgets.QWidget()
        self.onSuccessTab.setObjectName("onSuccessTab")
        self.successPassCheck = QtWidgets.QCheckBox(self.onSuccessTab)
        self.successPassCheck.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.successPassCheck.setObjectName("successPassCheck")
        self.tabWidget_2.addTab(self.onSuccessTab, "")
        self.onFailTab = QtWidgets.QWidget()
        self.onFailTab.setObjectName("onFailTab")
        self.failPassCheck = QtWidgets.QCheckBox(self.onFailTab)
        self.failPassCheck.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.failPassCheck.setObjectName("failPassCheck")
        self.tabWidget_2.addTab(self.onFailTab, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLine = QtWidgets.QLineEdit(self.frame)
        self.nameLine.setObjectName("nameLine")
        self.gridLayout.addWidget(self.nameLine, 0, 0, 1, 3)
        self.sequenceList = QtWidgets.QListWidget(self.frame)
        self.sequenceList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.sequenceList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequenceList.setObjectName("sequenceList")
        self.gridLayout.addWidget(self.sequenceList, 1, 0, 1, 3)
        self.upButton = QtWidgets.QPushButton(self.frame)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 2, 0, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.frame)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 2, 1, 1, 1)
        self.delButton = QtWidgets.QPushButton(self.frame)
        self.delButton.setObjectName("delButton")
        self.gridLayout.addWidget(self.delButton, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addAction(self.actionLoad)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionHelp)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python ImageMacro - Test Build"))
        self.imgButton.setText(_translate("MainWindow", "Insert"))
        self.clickTargetCheck.setText(_translate("MainWindow", "Click Target"))
        self.ImgNameLabel.setText(_translate("MainWindow", "No Image"))
        self.doubleClickCheck.setText(_translate("MainWindow", "Double Click"))
        self.groupBox.setTitle(_translate("MainWindow", "Loop"))
        self.label.setText(_translate("MainWindow", "Loop Count"))
        self.label_3.setText(_translate("MainWindow", "Loop Delay"))
        self.loopCountSpin_3.setSuffix(_translate("MainWindow", "s"))
        self.clickTargetCheck_2.setText(_translate("MainWindow", "Loop"))
        self.clickDelayCheck.setText(_translate("MainWindow", "Click Delay"))
        self.clickDelaySpin.setSuffix(_translate("MainWindow", "s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imgTab), _translate("MainWindow", "Image"))
        self.funcButton.setText(_translate("MainWindow", "Insert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.funcTab), _translate("MainWindow", "Functions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.debugTab), _translate("MainWindow", "Console"))
        self.successPassCheck.setText(_translate("MainWindow", "Pass"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.onSuccessTab), _translate("MainWindow", "On Success"))
        self.failPassCheck.setText(_translate("MainWindow", "Pass"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.onFailTab), _translate("MainWindow", "On Fail"))
        self.upButton.setText(_translate("MainWindow", "Move Up"))
        self.downButton.setText(_translate("MainWindow", "Move Down"))
        self.delButton.setText(_translate("MainWindow", "Delete"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionSave.setText(_translate("MainWindow", "Save (ctrl+s)"))
        self.actionLoad.setText(_translate("MainWindow", "Load (ctrl+l)"))
        self.actionExit.setText(_translate("MainWindow", "Exit (ctrl+q)"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
