# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Qt_UI/pymacro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 587)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(735, 587))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.methodList = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodList.sizePolicy().hasHeightForWidth())
        self.methodList.setSizePolicy(sizePolicy)
        self.methodList.setMinimumSize(QtCore.QSize(150, 0))
        self.methodList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.methodList.setAlternatingRowColors(True)
        self.methodList.setProperty("isWrapping", False)
        self.methodList.setResizeMode(QtWidgets.QListView.Fixed)
        self.methodList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.methodList.setSelectionRectVisible(True)
        self.methodList.setObjectName("methodList")
        item = QtWidgets.QListWidgetItem()
        self.methodList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.methodList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.methodList.addItem(item)
        self.gridLayout_2.addWidget(self.methodList, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(251, 101))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.onSuccessTab = QtWidgets.QWidget()
        self.onSuccessTab.setObjectName("onSuccessTab")
        self.successPassCheck = QtWidgets.QCheckBox(self.onSuccessTab)
        self.successPassCheck.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.successPassCheck.setObjectName("successPassCheck")
        self.tabWidget_2.addTab(self.onSuccessTab, "")
        self.onFailTab = QtWidgets.QWidget()
        self.onFailTab.setObjectName("onFailTab")
        self.failPassCheck = QtWidgets.QCheckBox(self.onFailTab)
        self.failPassCheck.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.failPassCheck.setObjectName("failPassCheck")
        self.tabWidget_2.addTab(self.onFailTab, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(251, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.imgTab = QtWidgets.QWidget()
        self.imgTab.setObjectName("imgTab")
        self.searchInsert = QtWidgets.QPushButton(self.imgTab)
        self.searchInsert.setGeometry(QtCore.QRect(170, 340, 61, 21))
        self.searchInsert.setObjectName("searchInsert")
        self.clickTargetCheck = QtWidgets.QCheckBox(self.imgTab)
        self.clickTargetCheck.setGeometry(QtCore.QRect(10, 340, 101, 20))
        self.clickTargetCheck.setObjectName("clickTargetCheck")
        self.searchImgLabel = QtWidgets.QLabel(self.imgTab)
        self.searchImgLabel.setGeometry(QtCore.QRect(10, 10, 226, 151))
        self.searchImgLabel.setAutoFillBackground(True)
        self.searchImgLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchImgLabel.setText("")
        self.searchImgLabel.setObjectName("searchImgLabel")
        self.serachImgNameLabel = QtWidgets.QLabel(self.imgTab)
        self.serachImgNameLabel.setGeometry(QtCore.QRect(11, 145, 221, 20))
        self.serachImgNameLabel.setLineWidth(0)
        self.serachImgNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.serachImgNameLabel.setObjectName("serachImgNameLabel")
        self.groupBox = QtWidgets.QGroupBox(self.imgTab)
        self.groupBox.setGeometry(QtCore.QRect(130, 200, 101, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(15, 20, 81, 20))
        self.label.setObjectName("label")
        self.trialsCountSpin = QtWidgets.QSpinBox(self.groupBox)
        self.trialsCountSpin.setGeometry(QtCore.QRect(15, 40, 71, 21))
        self.trialsCountSpin.setObjectName("trialsCountSpin")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(14, 70, 81, 20))
        self.label_3.setObjectName("label_3")
        self.trialsIntervalSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.trialsIntervalSpin.setGeometry(QtCore.QRect(14, 90, 71, 21))
        self.trialsIntervalSpin.setMaximum(10000.0)
        self.trialsIntervalSpin.setSingleStep(0.05)
        self.trialsIntervalSpin.setProperty("value", 0.2)
        self.trialsIntervalSpin.setObjectName("trialsIntervalSpin")
        self.groupBox_2 = QtWidgets.QGroupBox(self.imgTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 111, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label_2.setObjectName("label_2")
        self.clickCountSpin = QtWidgets.QSpinBox(self.groupBox_2)
        self.clickCountSpin.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.clickCountSpin.setObjectName("clickCountSpin")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.label_4.setObjectName("label_4")
        self.clickIntervalSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.clickIntervalSpin.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.clickIntervalSpin.setMaximum(10000.0)
        self.clickIntervalSpin.setSingleStep(0.05)
        self.clickIntervalSpin.setProperty("value", 0.2)
        self.clickIntervalSpin.setObjectName("clickIntervalSpin")
        self.searchImgLoadButton = QtWidgets.QPushButton(self.imgTab)
        self.searchImgLoadButton.setGeometry(QtCore.QRect(161, 164, 75, 23))
        self.searchImgLoadButton.setObjectName("searchImgLoadButton")
        self.searchImgClearButton = QtWidgets.QPushButton(self.imgTab)
        self.searchImgClearButton.setGeometry(QtCore.QRect(80, 164, 75, 23))
        self.searchImgClearButton.setObjectName("searchImgClearButton")
        self.tabWidget.addTab(self.imgTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.countImgLabel = QtWidgets.QLabel(self.tab)
        self.countImgLabel.setGeometry(QtCore.QRect(10, 10, 226, 151))
        self.countImgLabel.setAutoFillBackground(True)
        self.countImgLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.countImgLabel.setText("")
        self.countImgLabel.setObjectName("countImgLabel")
        self.countImgNameLabel = QtWidgets.QLabel(self.tab)
        self.countImgNameLabel.setGeometry(QtCore.QRect(11, 145, 221, 20))
        self.countImgNameLabel.setLineWidth(0)
        self.countImgNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.countImgNameLabel.setObjectName("countImgNameLabel")
        self.countImgLoadButton = QtWidgets.QPushButton(self.tab)
        self.countImgLoadButton.setGeometry(QtCore.QRect(161, 164, 75, 23))
        self.countImgLoadButton.setObjectName("countImgLoadButton")
        self.countImgClearButton = QtWidgets.QPushButton(self.tab)
        self.countImgClearButton.setGeometry(QtCore.QRect(80, 164, 75, 23))
        self.countImgClearButton.setObjectName("countImgClearButton")
        self.countInsert = QtWidgets.QPushButton(self.tab)
        self.countInsert.setGeometry(QtCore.QRect(170, 340, 61, 21))
        self.countInsert.setObjectName("countInsert")
        self.tabWidget.addTab(self.tab, "")
        self.funcTab = QtWidgets.QWidget()
        self.funcTab.setObjectName("funcTab")
        self.funcButton = QtWidgets.QPushButton(self.funcTab)
        self.funcButton.setGeometry(QtCore.QRect(320, 460, 61, 21))
        self.funcButton.setObjectName("funcButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.funcTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.waitSpin = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.waitSpin.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.waitSpin.setDecimals(1)
        self.waitSpin.setMaximum(100000000000.0)
        self.waitSpin.setSingleStep(0.5)
        self.waitSpin.setProperty("value", 5.0)
        self.waitSpin.setObjectName("waitSpin")
        self.waitInsert = QtWidgets.QPushButton(self.groupBox_3)
        self.waitInsert.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.waitInsert.setObjectName("waitInsert")
        self.groupBox_4 = QtWidgets.QGroupBox(self.funcTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 100, 91, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.loopCountSpin = QtWidgets.QSpinBox(self.groupBox_4)
        self.loopCountSpin.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.loopCountSpin.setObjectName("loopCountSpin")
        self.LoopInsert = QtWidgets.QPushButton(self.groupBox_4)
        self.LoopInsert.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.LoopInsert.setObjectName("LoopInsert")
        self.groupBox_5 = QtWidgets.QGroupBox(self.funcTab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 91, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.loopCountSpin_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.loopCountSpin_2.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.loopCountSpin_2.setObjectName("loopCountSpin_2")
        self.clickInsert = QtWidgets.QPushButton(self.groupBox_5)
        self.clickInsert.setGeometry(QtCore.QRect(10, 150, 71, 21))
        self.clickInsert.setObjectName("clickInsert")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.label_6.setObjectName("label_6")
        self.loopCountSpin_3 = QtWidgets.QSpinBox(self.groupBox_5)
        self.loopCountSpin_3.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.loopCountSpin_3.setObjectName("loopCountSpin_3")
        self.coordFromImg = QtWidgets.QPushButton(self.groupBox_5)
        self.coordFromImg.setGeometry(QtCore.QRect(10, 120, 71, 21))
        self.coordFromImg.setObjectName("coordFromImg")
        self.tabWidget.addTab(self.funcTab, "")
        self.debugTab = QtWidgets.QWidget()
        self.debugTab.setObjectName("debugTab")
        self.tabWidget.addTab(self.debugTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.delButton = QtWidgets.QPushButton(self.frame)
        self.delButton.setObjectName("delButton")
        self.gridLayout.addWidget(self.delButton, 2, 2, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.frame)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 2, 1, 1, 1)
        self.upButton = QtWidgets.QPushButton(self.frame)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 2, 0, 1, 1)
        self.nameLine = QtWidgets.QLineEdit(self.frame)
        self.nameLine.setObjectName("nameLine")
        self.gridLayout.addWidget(self.nameLine, 0, 0, 1, 3)
        self.sequenceList = QtWidgets.QListWidget(self.frame)
        self.sequenceList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.sequenceList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequenceList.setAlternatingRowColors(True)
        self.sequenceList.setMovement(QtWidgets.QListView.Static)
        self.sequenceList.setViewMode(QtWidgets.QListView.ListMode)
        self.sequenceList.setSelectionRectVisible(True)
        self.sequenceList.setObjectName("sequenceList")
        item = QtWidgets.QListWidgetItem()
        self.sequenceList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sequenceList.addItem(item)
        self.gridLayout.addWidget(self.sequenceList, 1, 0, 1, 3)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addAction(self.actionLoad)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionHelp)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python ImageMacro - Test Build"))
        __sortingEnabled = self.methodList.isSortingEnabled()
        self.methodList.setSortingEnabled(False)
        item = self.methodList.item(0)
        item.setText(_translate("MainWindow", "test1"))
        item = self.methodList.item(1)
        item.setText(_translate("MainWindow", "test2"))
        item = self.methodList.item(2)
        item.setText(_translate("MainWindow", "test3"))
        self.methodList.setSortingEnabled(__sortingEnabled)
        self.successPassCheck.setText(_translate("MainWindow", "Pass"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.onSuccessTab), _translate("MainWindow", "On Success"))
        self.failPassCheck.setText(_translate("MainWindow", "Pass"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.onFailTab), _translate("MainWindow", "On Fail"))
        self.searchInsert.setText(_translate("MainWindow", "Insert"))
        self.clickTargetCheck.setText(_translate("MainWindow", "Click Target"))
        self.serachImgNameLabel.setText(_translate("MainWindow", "No Image"))
        self.groupBox.setTitle(_translate("MainWindow", "Trials"))
        self.label.setText(_translate("MainWindow", "Count"))
        self.label_3.setText(_translate("MainWindow", "Interval"))
        self.trialsIntervalSpin.setSuffix(_translate("MainWindow", "s"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Click"))
        self.label_2.setText(_translate("MainWindow", "Count"))
        self.label_4.setText(_translate("MainWindow", "Interval"))
        self.clickIntervalSpin.setSuffix(_translate("MainWindow", "s"))
        self.searchImgLoadButton.setText(_translate("MainWindow", "Load Img"))
        self.searchImgClearButton.setText(_translate("MainWindow", "Clear Img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imgTab), _translate("MainWindow", "Search"))
        self.countImgNameLabel.setText(_translate("MainWindow", "No Image"))
        self.countImgLoadButton.setText(_translate("MainWindow", "Load Img"))
        self.countImgClearButton.setText(_translate("MainWindow", "Clear Img"))
        self.countInsert.setText(_translate("MainWindow", "Insert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Count"))
        self.funcButton.setText(_translate("MainWindow", "Insert"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Wait"))
        self.waitSpin.setSuffix(_translate("MainWindow", "s"))
        self.waitInsert.setText(_translate("MainWindow", "Insert"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Loop"))
        self.LoopInsert.setText(_translate("MainWindow", "Insert"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Click"))
        self.clickInsert.setText(_translate("MainWindow", "Insert"))
        self.label_5.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "Y"))
        self.coordFromImg.setText(_translate("MainWindow", "From Img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.funcTab), _translate("MainWindow", "Etc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.debugTab), _translate("MainWindow", "Console"))
        self.delButton.setText(_translate("MainWindow", "Delete"))
        self.downButton.setText(_translate("MainWindow", "Move Down"))
        self.upButton.setText(_translate("MainWindow", "Move Up"))
        __sortingEnabled = self.sequenceList.isSortingEnabled()
        self.sequenceList.setSortingEnabled(False)
        item = self.sequenceList.item(0)
        item.setText(_translate("MainWindow", "placeholder1"))
        item = self.sequenceList.item(1)
        item.setText(_translate("MainWindow", "placeholder2"))
        self.sequenceList.setSortingEnabled(__sortingEnabled)
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionSave.setText(_translate("MainWindow", "Save (ctrl+s)"))
        self.actionLoad.setText(_translate("MainWindow", "Load (ctrl+l)"))
        self.actionExit.setText(_translate("MainWindow", "Exit (ctrl+q)"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
