# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pymacro.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(735, 587)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(735, 587))
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_4 = QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy1)
        self.splitter.setOrientation(Qt.Horizontal)
        self.frame_2 = QFrame(self.splitter)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy1.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy1)
        self.frame_2.setMaximumSize(QSize(170, 16777215))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_2 = QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.methodList = QListWidget(self.frame_2)
        QListWidgetItem(self.methodList)
        QListWidgetItem(self.methodList)
        QListWidgetItem(self.methodList)
        self.methodList.setObjectName(u"methodList")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.methodList.sizePolicy().hasHeightForWidth())
        self.methodList.setSizePolicy(sizePolicy2)
        self.methodList.setMinimumSize(QSize(150, 0))
        self.methodList.setMaximumSize(QSize(150, 16777215))
        self.methodList.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.methodList.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.methodList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.methodList.setAlternatingRowColors(True)
        self.methodList.setProperty("isWrapping", False)
        self.methodList.setResizeMode(QListView.Fixed)
        self.methodList.setLayoutMode(QListView.SinglePass)
        self.methodList.setSpacing(1)
        self.methodList.setSelectionRectVisible(True)

        self.gridLayout_2.addWidget(self.methodList, 0, 0, 1, 1)

        self.logSaveCheck = QCheckBox(self.frame_2)
        self.logSaveCheck.setObjectName(u"logSaveCheck")
        self.logSaveCheck.setChecked(True)

        self.gridLayout_2.addWidget(self.logSaveCheck, 1, 0, 1, 1)

        self.splitter.addWidget(self.frame_2)
        self.frame_3 = QFrame(self.splitter)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_9 = QLabel(self.frame_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMaximumSize(QSize(16777215, 20))

        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)

        self.label_10 = QLabel(self.frame_3)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout_5.addWidget(self.label_10, 0, 1, 1, 1)

        self.onSuccessCombo = QComboBox(self.frame_3)
        self.onSuccessCombo.setObjectName(u"onSuccessCombo")

        self.gridLayout_5.addWidget(self.onSuccessCombo, 1, 0, 1, 1)

        self.onFailCombo = QComboBox(self.frame_3)
        self.onFailCombo.setObjectName(u"onFailCombo")

        self.gridLayout_5.addWidget(self.onFailCombo, 1, 1, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.runButton = QPushButton(self.frame_3)
        self.runButton.setObjectName(u"runButton")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.runButton)

        self.insertButton = QPushButton(self.frame_3)
        self.insertButton.setObjectName(u"insertButton")
        sizePolicy3.setHeightForWidth(self.insertButton.sizePolicy().hasHeightForWidth())
        self.insertButton.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.insertButton)

        self.editButton = QPushButton(self.frame_3)
        self.editButton.setObjectName(u"editButton")
        self.editButton.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.editButton)


        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.tabWidget = QTabWidget(self.frame_3)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy4)
        self.tabWidget.setMinimumSize(QSize(0, 431))
        self.tabWidget.setMaximumSize(QSize(252, 16777215))
        self.tabWidget.setUsesScrollButtons(True)
        self.imgTab = QWidget()
        self.imgTab.setObjectName(u"imgTab")
        self.searchImgLabel = QLabel(self.imgTab)
        self.searchImgLabel.setObjectName(u"searchImgLabel")
        self.searchImgLabel.setGeometry(QRect(10, 10, 226, 151))
        sizePolicy.setHeightForWidth(self.searchImgLabel.sizePolicy().hasHeightForWidth())
        self.searchImgLabel.setSizePolicy(sizePolicy)
        self.searchImgLabel.setMaximumSize(QSize(226, 151))
        self.searchImgLabel.setAutoFillBackground(True)
        self.searchImgLabel.setFrameShape(QFrame.StyledPanel)
        self.searchImgLabel.setScaledContents(False)
        self.searchImgLabel.setAlignment(Qt.AlignCenter)
        self.searchImgNameLabel = QLabel(self.imgTab)
        self.searchImgNameLabel.setObjectName(u"searchImgNameLabel")
        self.searchImgNameLabel.setGeometry(QRect(14, 146, 218, 12))
        self.searchImgNameLabel.setAutoFillBackground(False)
        self.searchImgNameLabel.setStyleSheet(u"background-color: rgba(0, 0, 0, 120);\n"
"color: rgb(255, 255, 255);")
        self.searchImgNameLabel.setFrameShadow(QFrame.Plain)
        self.searchImgNameLabel.setLineWidth(0)
        self.searchImgNameLabel.setTextFormat(Qt.RichText)
        self.searchImgNameLabel.setWordWrap(False)
        self.trialsGroup = QGroupBox(self.imgTab)
        self.trialsGroup.setObjectName(u"trialsGroup")
        self.trialsGroup.setGeometry(QRect(130, 200, 103, 131))
        self.label = QLabel(self.trialsGroup)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 20, 81, 20))
        self.trialsCountSpin = QSpinBox(self.trialsGroup)
        self.trialsCountSpin.setObjectName(u"trialsCountSpin")
        self.trialsCountSpin.setGeometry(QRect(15, 40, 71, 21))
        self.trialsCountSpin.setMinimum(1)
        self.trialsCountSpin.setMaximum(99999)
        self.trialsCountSpin.setValue(1)
        self.label_3 = QLabel(self.trialsGroup)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(14, 70, 81, 20))
        self.trialsIntervalSpin = QDoubleSpinBox(self.trialsGroup)
        self.trialsIntervalSpin.setObjectName(u"trialsIntervalSpin")
        self.trialsIntervalSpin.setGeometry(QRect(14, 90, 71, 21))
        self.trialsIntervalSpin.setMaximum(10000.000000000000000)
        self.trialsIntervalSpin.setSingleStep(0.050000000000000)
        self.trialsIntervalSpin.setValue(0.200000000000000)
        self.searchClickGroup = QGroupBox(self.imgTab)
        self.searchClickGroup.setObjectName(u"searchClickGroup")
        self.searchClickGroup.setEnabled(True)
        self.searchClickGroup.setGeometry(QRect(10, 200, 111, 131))
        self.searchClickGroup.setCheckable(False)
        self.searchClickGroup.setChecked(False)
        self.label_2 = QLabel(self.searchClickGroup)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 20, 81, 20))
        self.searchClickCount = QSpinBox(self.searchClickGroup)
        self.searchClickCount.setObjectName(u"searchClickCount")
        self.searchClickCount.setGeometry(QRect(20, 40, 71, 21))
        self.searchClickCount.setMaximum(99999)
        self.label_4 = QLabel(self.searchClickGroup)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 70, 81, 20))
        self.searchClickInterval = QDoubleSpinBox(self.searchClickGroup)
        self.searchClickInterval.setObjectName(u"searchClickInterval")
        self.searchClickInterval.setGeometry(QRect(20, 90, 71, 21))
        self.searchClickInterval.setMaximum(10000.000000000000000)
        self.searchClickInterval.setSingleStep(0.050000000000000)
        self.searchClickInterval.setValue(0.200000000000000)
        self.searchImgLoadButton = QPushButton(self.imgTab)
        self.searchImgLoadButton.setObjectName(u"searchImgLoadButton")
        self.searchImgLoadButton.setGeometry(QRect(161, 164, 75, 23))
        self.searchImgClearButton = QPushButton(self.imgTab)
        self.searchImgClearButton.setObjectName(u"searchImgClearButton")
        self.searchImgClearButton.setGeometry(QRect(80, 164, 75, 23))
        self.label_11 = QLabel(self.imgTab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(13, 340, 81, 20))
        self.searchPrecisionSpin = QSpinBox(self.imgTab)
        self.searchPrecisionSpin.setObjectName(u"searchPrecisionSpin")
        self.searchPrecisionSpin.setGeometry(QRect(72, 340, 51, 21))
        self.searchPrecisionSpin.setMaximum(100)
        self.searchPrecisionSpin.setValue(85)
        self.searchRandSpin = QSpinBox(self.imgTab)
        self.searchRandSpin.setObjectName(u"searchRandSpin")
        self.searchRandSpin.setGeometry(QRect(110, 370, 101, 21))
        self.searchRandSpin.setMaximum(9999)
        self.searchRandSpin.setStepType(QAbstractSpinBox.DefaultStepType)
        self.label_14 = QLabel(self.imgTab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(13, 370, 101, 20))
        self.tabWidget.addTab(self.imgTab, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.countImgLabel = QLabel(self.tab)
        self.countImgLabel.setObjectName(u"countImgLabel")
        self.countImgLabel.setGeometry(QRect(10, 10, 226, 151))
        sizePolicy.setHeightForWidth(self.countImgLabel.sizePolicy().hasHeightForWidth())
        self.countImgLabel.setSizePolicy(sizePolicy)
        self.countImgLabel.setMaximumSize(QSize(226, 151))
        self.countImgLabel.setAutoFillBackground(True)
        self.countImgLabel.setFrameShape(QFrame.StyledPanel)
        self.countImgLabel.setScaledContents(False)
        self.countImgNameLabel = QLabel(self.tab)
        self.countImgNameLabel.setObjectName(u"countImgNameLabel")
        self.countImgNameLabel.setGeometry(QRect(14, 146, 218, 12))
        self.countImgNameLabel.setAutoFillBackground(False)
        self.countImgNameLabel.setStyleSheet(u"background-color: rgba(0, 0, 0, 120);\n"
"color: rgb(255, 255, 255);")
        self.countImgNameLabel.setFrameShape(QFrame.NoFrame)
        self.countImgNameLabel.setFrameShadow(QFrame.Plain)
        self.countImgNameLabel.setLineWidth(0)
        self.countImgNameLabel.setTextFormat(Qt.RichText)
        self.countImgLoadButton = QPushButton(self.tab)
        self.countImgLoadButton.setObjectName(u"countImgLoadButton")
        self.countImgLoadButton.setGeometry(QRect(161, 164, 75, 23))
        self.countImgClearButton = QPushButton(self.tab)
        self.countImgClearButton.setObjectName(u"countImgClearButton")
        self.countImgClearButton.setGeometry(QRect(80, 164, 75, 23))
        self.countClickGroup = QGroupBox(self.tab)
        self.countClickGroup.setObjectName(u"countClickGroup")
        self.countClickGroup.setEnabled(True)
        self.countClickGroup.setGeometry(QRect(10, 200, 111, 131))
        self.countClickGroup.setCheckable(False)
        self.countClickGroup.setChecked(False)
        self.label_7 = QLabel(self.countClickGroup)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 20, 81, 20))
        self.countClickCount = QSpinBox(self.countClickGroup)
        self.countClickCount.setObjectName(u"countClickCount")
        self.countClickCount.setGeometry(QRect(20, 40, 71, 21))
        self.label_8 = QLabel(self.countClickGroup)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 70, 81, 20))
        self.countClickInterval = QDoubleSpinBox(self.countClickGroup)
        self.countClickInterval.setObjectName(u"countClickInterval")
        self.countClickInterval.setGeometry(QRect(20, 90, 71, 21))
        self.countClickInterval.setMaximum(10000.000000000000000)
        self.countClickInterval.setSingleStep(0.050000000000000)
        self.countClickInterval.setValue(0.200000000000000)
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(13, 340, 81, 20))
        self.countPrecisionSpin = QSpinBox(self.tab)
        self.countPrecisionSpin.setObjectName(u"countPrecisionSpin")
        self.countPrecisionSpin.setGeometry(QRect(72, 340, 51, 21))
        self.countPrecisionSpin.setMaximum(100)
        self.countPrecisionSpin.setValue(85)
        self.countRandSpin = QSpinBox(self.tab)
        self.countRandSpin.setObjectName(u"countRandSpin")
        self.countRandSpin.setGeometry(QRect(110, 370, 101, 21))
        self.countRandSpin.setMaximum(9999)
        self.countRandSpin.setStepType(QAbstractSpinBox.DefaultStepType)
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(13, 370, 101, 20))
        self.countClickGroup_2 = QGroupBox(self.tab)
        self.countClickGroup_2.setObjectName(u"countClickGroup_2")
        self.countClickGroup_2.setEnabled(True)
        self.countClickGroup_2.setGeometry(QRect(130, 200, 111, 131))
        self.countClickGroup_2.setCheckable(False)
        self.countClickGroup_2.setChecked(False)
        self.label_17 = QLabel(self.countClickGroup_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 20, 81, 20))
        self.countThreshold = QSpinBox(self.countClickGroup_2)
        self.countThreshold.setObjectName(u"countThreshold")
        self.countThreshold.setGeometry(QRect(20, 40, 71, 21))
        self.countThreshold.setMaximum(75)
        self.countThreshold.setValue(5)
        self.countThreshold.setDisplayIntegerBase(10)
        self.tabWidget.addTab(self.tab, "")
        self.funcTab = QWidget()
        self.funcTab.setObjectName(u"funcTab")
        self.funcButton = QPushButton(self.funcTab)
        self.funcButton.setObjectName(u"funcButton")
        self.funcButton.setGeometry(QRect(320, 460, 61, 21))
        self.waitGroup = QGroupBox(self.funcTab)
        self.waitGroup.setObjectName(u"waitGroup")
        self.waitGroup.setEnabled(True)
        self.waitGroup.setGeometry(QRect(10, 10, 91, 51))
        self.waitGroup.setCheckable(False)
        self.waitSpin = QDoubleSpinBox(self.waitGroup)
        self.waitSpin.setObjectName(u"waitSpin")
        self.waitSpin.setGeometry(QRect(10, 20, 71, 21))
        self.waitSpin.setDecimals(1)
        self.waitSpin.setMaximum(100000000000.000000000000000)
        self.waitSpin.setSingleStep(0.500000000000000)
        self.waitSpin.setValue(5.000000000000000)
        self.loopGroup = QGroupBox(self.funcTab)
        self.loopGroup.setObjectName(u"loopGroup")
        self.loopGroup.setEnabled(True)
        self.loopGroup.setGeometry(QRect(10, 70, 91, 51))
        self.loopGroup.setCheckable(False)
        self.loopCountSpin = QSpinBox(self.loopGroup)
        self.loopCountSpin.setObjectName(u"loopCountSpin")
        self.loopCountSpin.setGeometry(QRect(10, 20, 71, 21))
        self.loopCountSpin.setMinimum(-1)
        self.loopCountSpin.setMaximum(9999)
        self.loopCountSpin.setValue(1)
        self.clickGroup = QGroupBox(self.funcTab)
        self.clickGroup.setObjectName(u"clickGroup")
        self.clickGroup.setGeometry(QRect(10, 130, 91, 111))
        self.clickFromImg = QPushButton(self.clickGroup)
        self.clickFromImg.setObjectName(u"clickFromImg")
        self.clickFromImg.setGeometry(QRect(10, 80, 71, 21))
        self.label_6 = QLabel(self.clickGroup)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 21, 20))
        self.label_5 = QLabel(self.clickGroup)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 21, 20))
        self.clickX = QSpinBox(self.clickGroup)
        self.clickX.setObjectName(u"clickX")
        self.clickX.setGeometry(QRect(40, 20, 41, 22))
        self.clickX.setFrame(True)
        self.clickX.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.clickX.setMaximum(99999)
        self.clickY = QSpinBox(self.clickGroup)
        self.clickY.setObjectName(u"clickY")
        self.clickY.setGeometry(QRect(40, 50, 41, 22))
        self.clickY.setFrame(True)
        self.clickY.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.clickY.setMaximum(99999)
        self.varGroup = QGroupBox(self.funcTab)
        self.varGroup.setObjectName(u"varGroup")
        self.varGroup.setGeometry(QRect(110, 10, 127, 251))
        self.newValueRadio = QRadioButton(self.varGroup)
        self.newValueRadio.setObjectName(u"newValueRadio")
        self.newValueRadio.setGeometry(QRect(10, 20, 101, 16))
        self.newValueRadio.setChecked(True)
        self.variableArg2 = QComboBox(self.varGroup)
        self.variableArg2.setObjectName(u"variableArg2")
        self.variableArg2.setGeometry(QRect(10, 160, 101, 22))
        self.variableArg1 = QComboBox(self.varGroup)
        self.variableArg1.setObjectName(u"variableArg1")
        self.variableArg1.setGeometry(QRect(10, 100, 101, 22))
        self.operatorArg1 = QComboBox(self.varGroup)
        self.operatorArg1.setObjectName(u"operatorArg1")
        self.operatorArg1.setGeometry(QRect(40, 130, 41, 22))
        self.variableArg3 = QComboBox(self.varGroup)
        self.variableArg3.setObjectName(u"variableArg3")
        self.variableArg3.setGeometry(QRect(10, 220, 101, 22))
        self.operatorArg2 = QComboBox(self.varGroup)
        self.operatorArg2.addItem("")
        self.operatorArg2.addItem("")
        self.operatorArg2.setObjectName(u"operatorArg2")
        self.operatorArg2.setGeometry(QRect(40, 190, 41, 22))
        self.calRadio = QRadioButton(self.varGroup)
        self.calRadio.setObjectName(u"calRadio")
        self.calRadio.setGeometry(QRect(10, 80, 90, 16))
        self.variableLine = QLineEdit(self.varGroup)
        self.variableLine.setObjectName(u"variableLine")
        self.variableLine.setGeometry(QRect(10, 40, 113, 20))
        self.dragGroup = QGroupBox(self.funcTab)
        self.dragGroup.setObjectName(u"dragGroup")
        self.dragGroup.setGeometry(QRect(10, 250, 91, 151))
        self.dragFromImg = QPushButton(self.dragGroup)
        self.dragFromImg.setObjectName(u"dragFromImg")
        self.dragFromImg.setGeometry(QRect(10, 120, 71, 21))
        self.label_15 = QLabel(self.dragGroup)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 20, 81, 20))
        self.dragFromX = QSpinBox(self.dragGroup)
        self.dragFromX.setObjectName(u"dragFromX")
        self.dragFromX.setGeometry(QRect(10, 40, 31, 22))
        self.dragFromX.setFrame(True)
        self.dragFromX.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.dragFromX.setMaximum(99999)
        self.dragFromY = QSpinBox(self.dragGroup)
        self.dragFromY.setObjectName(u"dragFromY")
        self.dragFromY.setGeometry(QRect(50, 40, 31, 22))
        self.dragFromY.setFrame(True)
        self.dragFromY.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.dragFromY.setMaximum(99999)
        self.label_16 = QLabel(self.dragGroup)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 70, 81, 20))
        self.dragToY = QSpinBox(self.dragGroup)
        self.dragToY.setObjectName(u"dragToY")
        self.dragToY.setGeometry(QRect(50, 90, 31, 22))
        self.dragToY.setFrame(True)
        self.dragToY.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.dragToY.setMaximum(99999)
        self.dragToX = QSpinBox(self.dragGroup)
        self.dragToX.setObjectName(u"dragToX")
        self.dragToX.setGeometry(QRect(10, 90, 31, 22))
        self.dragToX.setFrame(True)
        self.dragToX.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.dragToX.setMaximum(99999)
        self.tabWidget.addTab(self.funcTab, "")
        self.debugTab = QWidget()
        self.debugTab.setObjectName(u"debugTab")
        self.gridLayout_6 = QGridLayout(self.debugTab)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.outputTextEdit = QTextEdit(self.debugTab)
        self.outputTextEdit.setObjectName(u"outputTextEdit")
        self.outputTextEdit.setStyleSheet(u"background-color: rgb(30, 30, 30);\n"
"color: rgb(230, 230, 230);")
        self.outputTextEdit.setFrameShape(QFrame.NoFrame)
        self.outputTextEdit.setFrameShadow(QFrame.Sunken)
        self.outputTextEdit.setLineWidth(1)
        self.outputTextEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.outputTextEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.outputTextEdit.setAutoFormatting(QTextEdit.AutoNone)
        self.outputTextEdit.setUndoRedoEnabled(False)
        self.outputTextEdit.setLineWrapMode(QTextEdit.WidgetWidth)
        self.outputTextEdit.setLineWrapColumnOrWidth(0)
        self.outputTextEdit.setReadOnly(True)

        self.gridLayout_6.addWidget(self.outputTextEdit, 1, 0, 1, 1)

        self.lockLogCheck = QCheckBox(self.debugTab)
        self.lockLogCheck.setObjectName(u"lockLogCheck")

        self.gridLayout_6.addWidget(self.lockLogCheck, 0, 0, 1, 1)

        self.tabWidget.addTab(self.debugTab, "")

        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.splitter.addWidget(self.frame_3)
        self.frame = QFrame(self.splitter)
        self.frame.setObjectName(u"frame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(2)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy5)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.sequenceList = QListWidget(self.frame)
        QListWidgetItem(self.sequenceList)
        QListWidgetItem(self.sequenceList)
        self.sequenceList.setObjectName(u"sequenceList")
        self.sequenceList.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.sequenceList.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.sequenceList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.sequenceList.setAlternatingRowColors(True)
        self.sequenceList.setMovement(QListView.Static)
        self.sequenceList.setViewMode(QListView.ListMode)
        self.sequenceList.setSelectionRectVisible(True)

        self.gridLayout.addWidget(self.sequenceList, 1, 0, 1, 3)

        self.delButton = QPushButton(self.frame)
        self.delButton.setObjectName(u"delButton")

        self.gridLayout.addWidget(self.delButton, 2, 2, 1, 1)

        self.downButton = QPushButton(self.frame)
        self.downButton.setObjectName(u"downButton")

        self.gridLayout.addWidget(self.downButton, 2, 1, 1, 1)

        self.upButton = QPushButton(self.frame)
        self.upButton.setObjectName(u"upButton")

        self.gridLayout.addWidget(self.upButton, 2, 0, 1, 1)

        self.nameLine = QLineEdit(self.frame)
        self.nameLine.setObjectName(u"nameLine")

        self.gridLayout.addWidget(self.nameLine, 0, 0, 1, 3)

        self.splitter.addWidget(self.frame)

        self.gridLayout_4.addWidget(self.splitter, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 735, 21))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addAction(self.actionLoad)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Python Macro Sequencer - Test v0.0.4", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save (ctrl+s)", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load (ctrl+l)", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit (ctrl+q)", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))

        __sortingEnabled = self.methodList.isSortingEnabled()
        self.methodList.setSortingEnabled(False)
        ___qlistwidgetitem = self.methodList.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"test1", None));
        ___qlistwidgetitem1 = self.methodList.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"test2", None));
        ___qlistwidgetitem2 = self.methodList.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"test3", None));
        self.methodList.setSortingEnabled(__sortingEnabled)

        self.logSaveCheck.setText(QCoreApplication.translate("MainWindow", u"Save log to file", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"On Success", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"On Fail", None))
        self.runButton.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.insertButton.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.editButton.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.searchImgLabel.setText("")
        self.searchImgNameLabel.setText(QCoreApplication.translate("MainWindow", u"No Image", None))
        self.trialsGroup.setTitle(QCoreApplication.translate("MainWindow", u"Trials", None))
#if QT_CONFIG(tooltip)
        self.label.setToolTip(QCoreApplication.translate("MainWindow", u"Number of image match trials until failure.", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Count", None))
#if QT_CONFIG(tooltip)
        self.trialsCountSpin.setToolTip(QCoreApplication.translate("MainWindow", u"Number of image match trials until failure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(QCoreApplication.translate("MainWindow", u"Interval between trials.", None))
#endif // QT_CONFIG(tooltip)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Interval", None))
#if QT_CONFIG(tooltip)
        self.trialsIntervalSpin.setToolTip(QCoreApplication.translate("MainWindow", u"Interval between trials.", None))
#endif // QT_CONFIG(tooltip)
        self.trialsIntervalSpin.setSuffix(QCoreApplication.translate("MainWindow", u"s", None))
#if QT_CONFIG(tooltip)
        self.searchClickGroup.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.searchClickGroup.setTitle(QCoreApplication.translate("MainWindow", u"Click", None))
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(QCoreApplication.translate("MainWindow", u"Number of clicks when image is matched.", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Count", None))
#if QT_CONFIG(tooltip)
        self.searchClickCount.setToolTip(QCoreApplication.translate("MainWindow", u"Number of clicks when image is matched.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip(QCoreApplication.translate("MainWindow", u"Interval between each clicks.", None))
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Interval", None))
#if QT_CONFIG(tooltip)
        self.searchClickInterval.setToolTip(QCoreApplication.translate("MainWindow", u"Interval between each clicks.", None))
#endif // QT_CONFIG(tooltip)
        self.searchClickInterval.setSuffix(QCoreApplication.translate("MainWindow", u"s", None))
        self.searchImgLoadButton.setText(QCoreApplication.translate("MainWindow", u"Load Img", None))
        self.searchImgClearButton.setText(QCoreApplication.translate("MainWindow", u"Clear Img", None))
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Sets <span style=\" font-weight:600;\">minimum </span>similarity when matching image. Usually ~99% similarity is hardly useful when used in emulators due to inaccurate simulation.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Precision", None))
#if QT_CONFIG(tooltip)
        self.searchPrecisionSpin.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Sets <span style=\" font-weight:600;\">minimum </span>similarity when matching image. Usually ~99% similarity is hardly useful when used in emulators due to inaccurate simulation.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.searchPrecisionSpin.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.searchPrecisionSpin.setPrefix("")
#if QT_CONFIG(tooltip)
        self.searchRandSpin.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Drift click position <span style=\" font-weight:600;\">randomly</span> to avoid macro detection in some games.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.searchRandSpin.setSuffix(QCoreApplication.translate("MainWindow", u" Pixel(s)", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Random Offset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imgTab), QCoreApplication.translate("MainWindow", u"Search", None))
        self.countImgLabel.setText("")
        self.countImgNameLabel.setText(QCoreApplication.translate("MainWindow", u"No Image", None))
        self.countImgLoadButton.setText(QCoreApplication.translate("MainWindow", u"Load Img", None))
        self.countImgClearButton.setText(QCoreApplication.translate("MainWindow", u"Clear Img", None))
        self.countClickGroup.setTitle(QCoreApplication.translate("MainWindow", u"Click", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Count", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Interval", None))
        self.countClickInterval.setSuffix(QCoreApplication.translate("MainWindow", u"s", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Precision", None))
        self.countPrecisionSpin.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.countPrecisionSpin.setPrefix("")
#if QT_CONFIG(tooltip)
        self.countRandSpin.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Drift click position <span style=\" font-weight:600;\">randomly</span> to avoid macro detection in some games.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.countRandSpin.setSuffix(QCoreApplication.translate("MainWindow", u" Pixel(s)", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Random Offset", None))
        self.countClickGroup_2.setTitle(QCoreApplication.translate("MainWindow", u"Extra", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Threshold", None))
#if QT_CONFIG(tooltip)
        self.countThreshold.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Configs max percent of <span style=\" font-weight:600;\">clipping</span> between separated matches.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.countThreshold.setSuffix(QCoreApplication.translate("MainWindow", u" %", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Count", None))
        self.funcButton.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.waitGroup.setTitle(QCoreApplication.translate("MainWindow", u"Wait", None))
        self.waitSpin.setSuffix(QCoreApplication.translate("MainWindow", u"s", None))
        self.loopGroup.setTitle(QCoreApplication.translate("MainWindow", u"Loop", None))
#if QT_CONFIG(tooltip)
        self.loopCountSpin.setToolTip(QCoreApplication.translate("MainWindow", u"Set -1 for infinite loop.", None))
#endif // QT_CONFIG(tooltip)
        self.clickGroup.setTitle(QCoreApplication.translate("MainWindow", u"Click", None))
        self.clickFromImg.setText(QCoreApplication.translate("MainWindow", u"From Img", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.varGroup.setTitle(QCoreApplication.translate("MainWindow", u"Variable", None))
        self.newValueRadio.setText(QCoreApplication.translate("MainWindow", u"New Variable", None))
        self.variableArg2.setCurrentText("")
        self.variableArg1.setCurrentText("")
        self.operatorArg1.setCurrentText("")
        self.variableArg3.setCurrentText("")
        self.operatorArg2.setItemText(0, "")
        self.operatorArg2.setItemText(1, QCoreApplication.translate("MainWindow", u"=", None))

        self.operatorArg2.setCurrentText("")
        self.calRadio.setText(QCoreApplication.translate("MainWindow", u"Calculation", None))
        self.variableLine.setText("")
        self.variableLine.setPlaceholderText(QCoreApplication.translate("MainWindow", u" Type value here..", None))
        self.dragGroup.setTitle(QCoreApplication.translate("MainWindow", u"Drag", None))
        self.dragFromImg.setText(QCoreApplication.translate("MainWindow", u"From Img", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"From X / Y", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"To    X / Y", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.funcTab), QCoreApplication.translate("MainWindow", u"Etc", None))
        self.outputTextEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Standby", None))
        self.lockLogCheck.setText(QCoreApplication.translate("MainWindow", u"Lock to Log tab", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.debugTab), QCoreApplication.translate("MainWindow", u"Log", None))

        __sortingEnabled1 = self.sequenceList.isSortingEnabled()
        self.sequenceList.setSortingEnabled(False)
        ___qlistwidgetitem3 = self.sequenceList.item(0)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"placeholder1", None));
        ___qlistwidgetitem4 = self.sequenceList.item(1)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u"placeholder2", None));
        self.sequenceList.setSortingEnabled(__sortingEnabled1)

        self.delButton.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.downButton.setText(QCoreApplication.translate("MainWindow", u"Move Down", None))
        self.upButton.setText(QCoreApplication.translate("MainWindow", u"Move Up", None))
        self.nameLine.setInputMask("")
        self.nameLine.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Name..", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
    # retranslateUi

